# Generated by Django 4.1.7 on 2023-05-17 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0010_alter_profile_name_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('В работе', 'В работе'), ('C', 'Выполнено')], default='В обработке', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
